worker_processes 1;
pid /mnt/c/Users/WYH/Desktop/polarisctf招新赛/pwn/pwn-ct/lab/run/nginx.pid;

events {
    worker_connections 128;
}

http {
    default_type application/octet-stream;

    client_body_temp_path /mnt/c/Users/WYH/Desktop/polarisctf招新赛/pwn/pwn-ct/lab/run/body_temp;
    proxy_temp_path /mnt/c/Users/WYH/Desktop/polarisctf招新赛/pwn/pwn-ct/lab/run/proxy_temp;
    fastcgi_temp_path /mnt/c/Users/WYH/Desktop/polarisctf招新赛/pwn/pwn-ct/lab/run/fastcgi_temp;
    uwsgi_temp_path /mnt/c/Users/WYH/Desktop/polarisctf招新赛/pwn/pwn-ct/lab/run/uwsgi_temp;
    scgi_temp_path /mnt/c/Users/WYH/Desktop/polarisctf招新赛/pwn/pwn-ct/lab/run/scgi_temp;

    server {
        listen 8080;
        server_name iot-guardian.local;

        root /mnt/c/Users/WYH/Desktop/polarisctf招新赛/pwn/pwn-ct/lab/html;
        index index.html;

        location /static {
            alias /mnt/c/Users/WYH/Desktop/polarisctf招新赛/pwn/pwn-ct/lab/static/;
        }

        location /api/devices {
            proxy_pass http://127.0.0.1:3001;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        location /api/config/ {
            proxy_pass http://127.0.0.1:3002;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        location /api/logs {
            proxy_pass http://127.0.0.1:3003;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        location /admin/config/ {
            proxy_pass http://127.0.0.1:3002/api/config/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        add_header X-Content-Type-Options nosniff;
        add_header X-Frame-Options DENY;

        location ~ /\. {
            deny all;
        }

        access_log /mnt/c/Users/WYH/Desktop/polarisctf招新赛/pwn/pwn-ct/lab/logs/access.log;
        error_log /mnt/c/Users/WYH/Desktop/polarisctf招新赛/pwn/pwn-ct/lab/logs/error.log info;
    }
}
